// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.constants.DebugConstants;
import frc.robot.constants.Devices;

import com.revrobotics.spark.SparkBase;
import com.revrobotics.spark.SparkMax;
import com.revrobotics.spark.SparkLowLevel.MotorType;
import com.revrobotics.spark.config.SparkMaxConfig;
import com.revrobotics.spark.config.SparkBaseConfig.IdleMode;

/**
 *
 */
public class Feeder extends SubsystemBase {

    private SparkMax feederMotor;
    private SparkMaxConfig feederMotorConfigs;
    private DigitalInput ballSensor;

    public enum FeederMode {

        Stopped("Stopped"),
        ManualFeed("Manual Feed"),
        AutoFeed("Auto Feeding"),
        AutoFeedAdvance("Auto Feed Advance");

        public final String displayName;

        private FeederMode(String displayName) {
            this.displayName = displayName;
        }

    }

    private FeederMode mode = FeederMode.Stopped;

    private double speed = 0; // Requested speed

    private double dashboardCounter = 0;

    public Feeder() {

        feederMotor = new SparkMax(Devices.CANDeviceAddress.ShooterFeed.id, MotorType.kBrushed);
        feederMotorConfigs = new SparkMaxConfig();
        ballSensor = new DigitalInput(0);

        this.buildMotorConfigs();
        this.applyMotorConfigs();

    }

    private void buildMotorConfigs() {
        this.feederMotorConfigs.idleMode(IdleMode.kBrake);
        this.feederMotorConfigs.inverted(true);
        this.feederMotorConfigs.smartCurrentLimit(15);
    }

    private void applyMotorConfigs() {
        this.feederMotor.configure(feederMotorConfigs, SparkBase.ResetMode.kResetSafeParameters,
                SparkBase.PersistMode.kPersistParameters);
    }

    @Override
    public void periodic() {
        switch (mode) {
            case Stopped:
                feederMotor.set(0.0);
                break;
            case ManualFeed:
                feederMotor.set(speed);
                break;
            case AutoFeed:

                break;
            case AutoFeedAdvance:

                break;
        }

        if (DebugConstants.Logging.enableFeeder && ++dashboardCounter >= 5) {
            // Update Dashboard
            SmartDashboard.putString("Feeder: Mode", mode.displayName);
            SmartDashboard.putNumber("Feeder: Power", speed);
            SmartDashboard.putBoolean("Feeder: Ball Seen", ballSeen());

            dashboardCounter = 0;
        }
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    public void setMode(FeederMode newMode) {
        mode = newMode;
    }

    public FeederMode getMode() {
        return mode;
    }

    public double getSpeed() {
        return speed;
    }

    public void setSpeed(double speedCommanded) {
        this.speed = speedCommanded;
    }

    public void setState(double speedCommanded, FeederMode newMode) {
        this.speed = speedCommanded;
        this.mode = newMode;
    }

    public boolean ballSeen() {
        return this.ballSensor.get();

    }

    public void reset() {
        setMode(FeederMode.Stopped);
        setSpeed(0.0);
    }
}
