// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.constants.DebugConstants;
import frc.robot.constants.Devices;

import com.revrobotics.spark.SparkBase;
import com.revrobotics.spark.SparkMax;
import com.revrobotics.spark.SparkLowLevel.MotorType;
import com.revrobotics.spark.config.SparkMaxConfig;
import com.revrobotics.spark.config.SparkBaseConfig.IdleMode;

/**
 *
 */
public class Funnel extends SubsystemBase {

    private SparkMax funnelMotor;
    private SparkMaxConfig funnelMotorConfigs;

    public enum FunnelMode {

        Stopped("Stopped"),
        ManualFeed("Manual Feed"),
        AutoFeed("Auto Feeding"),
        AutoAdvance("Auto Advance");

        public final String displayName;

        private FunnelMode(String displayName) {
            this.displayName = displayName;
        }

    }

    private FunnelMode mode = FunnelMode.Stopped;

    private double speed = 0; // Requested speed

    private double dashboardCounter = 0;

    public Funnel() {

        funnelMotor = new SparkMax(Devices.CANDeviceAddress.CargoFunnel.id, MotorType.kBrushed);
        funnelMotorConfigs = new SparkMaxConfig();

        this.buildMotorConfigs();
        this.applyMotorConfigs();

    }

    private void buildMotorConfigs() {
        this.funnelMotorConfigs.idleMode(IdleMode.kBrake);
        this.funnelMotorConfigs.inverted(false);
        this.funnelMotorConfigs.smartCurrentLimit(15);
    }

    private void applyMotorConfigs() {
        this.funnelMotor.configure(funnelMotorConfigs, SparkBase.ResetMode.kResetSafeParameters,
                SparkBase.PersistMode.kPersistParameters);
    }

    @Override
    public void periodic() {
        switch (mode) {
            case Stopped:
                funnelMotor.set(0.0);
                break;
            case ManualFeed:
                funnelMotor.set(speed);
                break;
            case AutoFeed:

                break;
            case AutoAdvance:

                break;
        }

        if (DebugConstants.Logging.enableFunnel && ++dashboardCounter >= 5) {
            // Update Dashboard
            SmartDashboard.putString("Funnel: Mode", mode.displayName);
            SmartDashboard.putNumber("Funnel: Power", speed);

            dashboardCounter = 0;
        }
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    public void setMode(FunnelMode newMode) {
        mode = newMode;
    }

    public FunnelMode getMode() {
        return mode;
    }

    public double getSpeed() {
        return speed;
    }

    public void setSpeed(double speedCommanded) {
        this.speed = speedCommanded;
    }

    public void setState(double speedCommanded, FunnelMode newMode) {
        this.speed = speedCommanded;
        this.mode = newMode;
    }

    public void reset() {
        setMode(FunnelMode.Stopped);
        setSpeed(0.0);
    }
}
