// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.constants.DebugConstants;
import frc.robot.constants.Devices;
import frc.robot.constants.IntakeConstants;

import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.DutyCycleOut;

// import com.ctre.phoenix.motorcontrol.ControlMode;
// import com.ctre.phoenix.motorcontrol.NeutralMode;

// import com.ctre.phoenix.motorcontrol.can.WPI_TalonFX;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.InvertedValue;
import com.ctre.phoenix6.signals.NeutralModeValue;

/**
 *
 */
public class Intake extends SubsystemBase {


    private TalonFX intakeMotor;
    private TalonFXConfiguration intakeMotorConfigs;
    private DutyCycleOut manualControlRequest;
   
    private boolean intakeCommanded = false;                 // Did driver request intake running
    private double speedCommanded = 0;                       // Requested speed

    private double dashboardCounter = 0;

    public Intake() {

        intakeMotor = new TalonFX(Devices.CANDeviceAddress.Intake.id);
        intakeMotorConfigs = new TalonFXConfiguration();
        manualControlRequest = new DutyCycleOut(0.0);

        this.buildMotorConfigs();
        this.applyMotorConfigs();

        intakeMotor.setNeutralMode(NeutralModeValue.Brake);

        addChild("Intake Motor", intakeMotor);
    }

    private void buildMotorConfigs() {
      this.intakeMotorConfigs.CurrentLimits.SupplyCurrentLimit = IntakeConstants.supplyCurrentLimit;
      this.intakeMotorConfigs.CurrentLimits.SupplyCurrentLowerLimit = IntakeConstants.supplyCurrentLowerLimit;
      this.intakeMotorConfigs.CurrentLimits.SupplyCurrentLowerTime = IntakeConstants.supplyCurrentLowerTime;
      this.intakeMotorConfigs.CurrentLimits.SupplyCurrentLimitEnable = IntakeConstants.supplyCurrentEnabled;
      this.intakeMotorConfigs.MotorOutput.Inverted = InvertedValue.CounterClockwise_Positive;
    }

    private void applyMotorConfigs() {
      this.intakeMotor.getConfigurator().apply(this.intakeMotorConfigs);
    }

    @Override
    public void periodic() {
        if (intakeCommanded) {
            intakeMotor.setControl(manualControlRequest.withOutput(speedCommanded));
        } else {
            intakeMotor.setControl(manualControlRequest.withOutput(0.0));
        }
        
        if (DebugConstants.Logging.enableIntake && ++dashboardCounter >= 5) {
            // Update Dashboard
            SmartDashboard.putBoolean("Intake: On", intakeCommanded);
            SmartDashboard.putNumber("Intake: Power", speedCommanded);

            dashboardCounter = 0;
        }
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    public void setIntakeCommanded (boolean commanded) {
        intakeCommanded = commanded;
    }

    public boolean getIntakeCommanded () {
        return intakeCommanded;
    }

    public double getSpeedCommanded() {
        return speedCommanded;
    }

    public void setSpeedCommanded(double speedCommanded) {
        this.speedCommanded = speedCommanded;
    }

    public void setState(double speedCommanded, boolean commanded) {
        this.speedCommanded = speedCommanded;
        this.intakeCommanded = commanded;
    }

    public void reset() {
        setIntakeCommanded(false);
        setSpeedCommanded(0.0);
    }
}